vich_uploader:
    db_driver: orm

    mappings:
        projet_image:
            uri_prefix: /images/imagesProjets
            upload_destination: '%kernel.project_dir%/public/images/imagesProjets'
            namer : Vich\UploaderBundle\Naming\SmartUniqueNamer
